#!/bin/bash

# bash_config

# Make vim the default editor
export EDITOR="vim"

# Make vim the default editor for SVN
export SVN_EDITOR="vim"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Set the Java home
export JAVA_HOME=`/usr/libexec/java_home`

# Dotfiles working copy
export DOT_HOME=$HOME/.dotfiles

# Dotfiles shell modules
export DOT_MODS=$DOT_HOME/shell/modules

# Enabled Dotfiles shell modules
export DOT_MODS_ACTIVE=$DOT_HOME/shell/enabled
