#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Marco Riello via @necolas - http://nicolasgallagher.com/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-latex      Suppress LaTeX updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/marc0uk/dotfiles/

Copyright (c) Nicolas Gallagher
Licensed under the MIT license.
EOT

}
