#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Nicolas Gallagher - http://nicolasgallagher.com/

Additional software to install

Browsers:
    Firefox
    Google Chrome

Development:
    iTerm 2
    Eclipse
    Intellij
    SourceTree
    Emacs
    XQuartz

Other:
    Dropbox
    Copy
    LightPaper
    Skype
    Twitter
    VLC
EOT

}
